# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'nodecap' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for nodecap
  pod 'SensorsAnalyticsSDK', :subspecs => ['ENABLE_REACT_NATIVE_APPCLICK']
end
